from ash_dal.exceptions import DALError


class DBConnectionError(DALError):
    pass
